### ISSUE TITLE
Anime Update Button has no feedback

### ISSUE THREAD

**Issue by TommyQCYang** [JasonCheungDev/UnofficialAnilistPlexServer#1]
**Preconditions**
Go to the anime tab
Press the update button

**Expected Results**
Button click feedback (eg animation or sound)

**Actual Results**
No button click feedback seen

**Last Known Pass**
Never

**Comment by JasonCheungDev** [comment]
Known issue, will update in a future release

**Comment by TommyQCYang** [comment]
bump

**Comment by JasonCheungDev** [comment]
users and animes page now shows an indicator if the server is currently working https://github.com/JasonCheungDev/UnofficialAnilistPlexServer/commit/2eac63bbd59b1de2a79f82513590cbd5763214fa
