### ISSUE TITLE
Titles showing as "No Results" even though they are in Plex

### ISSUE THREAD

**Issue by TommyQCYang** [JasonCheungDev/UnofficialAnilistPlexServer#2]
**Preconditions**
Go to the anime tab
Look for an anime that says "No Results" (eg Nisekoi in our case"

**Expected Results**
Anime is not in Plex

**Actual Results**
Anime is actually in Plex

**Last Known Pass**
Never

**Comment by JasonCheungDev** [comment]
Caused by corruption while manually editing some data, should be resolved now.
