### ISSUE TITLE
Support adding anime by tags

### ISSUE THREAD

**Issue by TommyQCYang** [JasonCheungDev/UnofficialAnilistPlexServer#4]
As an anime watcher, I want to be able to add anime to Plex without having to change its status to "watching", so that my watch statistics on Anilist aren't affected.

Anilist has a "custom list" feature that can be used as tags. I would like to be able to add anime to Plex by setting a tag like "List_DLoad2Plex".

**Comment by JasonCheungDev** [comment]
You can now use a custom list named "APS-Request" which functions the same as the "Watching" list https://github.com/JasonCheungDev/UnofficialAnilistPlexServer/commit/2eac63bbd59b1de2a79f82513590cbd5763214fa
